import { useState } from "react";
import { Button, Text, TextInput } from "@mantine/core";
import { useForm } from "@mantine/form";
import { notifications } from "@mantine/notifications";
import { IconArrowLeft } from "@tabler/icons-react";
import { asRichText, contentLimits, type ContentEntity, type TeamMemberContent } from "../../../shared/content-schema";
import { adminApi, type AdminResource } from "../api";
import { ImageCropper } from "../ImageCropper";
import { MediaPicker } from "../MediaPicker";
import { RichTextField } from "../RichTextField";
import { EditorFrame } from "../components/EditorFrame";
import { clone, type FieldSetter } from "../form";
import { RichTextList } from "../components/RepeatableFields";
import { TeamPreview } from "../components/PublicPreviews";

const blankTeamMember = (): TeamMemberContent => ({ name: "", role: "", image: "", bio: [asRichText("")], quote: asRichText("") });

export function TeamEditor({ entity, teamCount, teamIndex, onBack, onSaved, onPublish, onArchive, onDirtyChange, onRestored }: { onRestored?: () => Promise<void>; entity?: ContentEntity<TeamMemberContent>; teamCount: number; teamIndex: number; onBack: () => void; onSaved: (entity: ContentEntity, message?: string) => Promise<void>; onPublish: (resource: AdminResource, id: string) => Promise<void>; onArchive: (resource: AdminResource, id: string) => Promise<void>; onDirtyChange?: (dirty: boolean) => void }) {
  const form = useForm<TeamMemberContent>({ mode: "controlled", initialValues: clone(entity?.draft ?? entity?.published ?? blankTeamMember()), validate: { name: (value) => value.trim() ? null : "Il nome è obbligatorio", role: (value) => value.trim() ? null : "Il ruolo è obbligatorio", image: (value) => value ? null : "Scegli un ritratto" } });
  const [saving, setSaving] = useState(false); const set = form.setFieldValue as FieldSetter<TeamMemberContent>;
  const save = form.onSubmit(async (values) => { setSaving(true); try { const saved = await adminApi.save("team", entity?.id, values, entity?.displayOrder, entity?.updatedAt); form.resetDirty(values); await onSaved(saved); } catch (error) { notifications.show({ color: "red", message: error instanceof Error ? error.message : "Bozza non salvata" }); } finally { setSaving(false); } });
  if (!entity && teamCount >= 3) return <section className="editor-view"><header className="editor-header"><div><Button variant="subtle" color="dark" size="xs" leftSection={<IconArrowLeft size={15} stroke={1.8} />} onClick={onBack}>Archivio</Button><Text className="eyebrow">Persone</Text><h1>Il team è completo</h1></div></header><div className="empty-state"><p>Il collage pubblico è progettato per tre persone. Archivia un profilo esistente per liberare un posto, poi torna qui.</p><Button color="orange" onClick={onBack}>Vai all’archivio persone</Button></div></section>;
  return <form onSubmit={save}><EditorFrame title={entity ? form.values.name || "Persona senza nome" : "Nuova persona"} eyebrow="Persone" entity={entity} resource="team" onBack={onBack} onSave={() => save()} saving={saving} dirty={form.isDirty()} preview={<TeamPreview member={form.values} index={teamIndex} total={Math.max(teamCount, teamIndex + 1)} />} onPublish={onPublish} onArchive={onArchive} onDirtyChange={onDirtyChange} onRestored={onRestored}><section className="form-section"><div className="section-heading"><h2>Profilo</h2><p>{teamCount}/3 profili attivi. L’ordine si gestisce dall’archivio.</p></div><div className="form-grid"><TextInput label="Nome e cognome" required maxLength={contentLimits.team.name} value={form.values.name} onChange={(event) => set("name", event.currentTarget.value)} /><TextInput label="Ruolo" required maxLength={contentLimits.team.role} value={form.values.role} onChange={(event) => set("role", event.currentTarget.value)} /></div><MediaPicker label="Ritratto" required showPreview={false} altEditable={false} altHint="Il testo alternativo si costruisce dal nome inserito qui sopra." value={{ url: form.values.image, alt: `Ritratto di ${form.values.name || "persona del team"}`, assetId: form.values.imageAssetId }} onChange={(next) => { if (next.url === form.values.image && next.assetId === form.values.imageAssetId) return; form.setValues({ ...form.values, image: next.url, imageAssetId: next.assetId, imageCrop: undefined, imagePosition: undefined }); }} /><ImageCropper image={form.values.image} value={form.values.imageCrop} onChange={(imageCrop) => set("imageCrop", imageCrop)} title="Ritaglio del ritratto" description="Sposta il volto nell’area: è esattamente la parte che apparirà sul sito." /><RichTextList label="Bio" maxLength={contentLimits.team.bioParagraph} values={form.values.bio} onChange={(next) => set("bio", next)} /><RichTextField label="Citazione" maxLength={contentLimits.team.quote} value={form.values.quote} onChange={(next) => set("quote", next)} /><TextInput label="Autore citazione" maxLength={contentLimits.team.quoteAuthor} value={form.values.quoteAuthor ?? ""} onChange={(event) => set("quoteAuthor", event.currentTarget.value || undefined)} /></section></EditorFrame></form>;
}
