import { useMemo } from "react";
import { ActionIcon, Badge, Button, Group, Menu, SegmentedControl, Text, TextInput, Tooltip, UnstyledButton } from "@mantine/core";
import { useForm } from "@mantine/form";
import { IconArrowDown, IconArrowUp, IconDots } from "@tabler/icons-react";
import type { ContentEntity, ProjectContent, TeamMemberContent } from "../../../shared/content-schema";
import { archiveDate, changedSincePublication, statusLabel } from "../content-status";

type ArchiveEntity = ContentEntity<ProjectContent | TeamMemberContent>;
export function ArchiveView({ section, items, isAdmin, teamFull, onNew, onOpen, onMove, onRestore, onDuplicate, onPublish, onArchive }: { section: "projects" | "team"; items: ArchiveEntity[]; isAdmin: boolean; teamFull: boolean; onNew: () => void; onOpen: (id: string) => void; onMove: (item: ArchiveEntity, neighbour: ArchiveEntity) => void; onRestore: (id: string) => void; onDuplicate: (item: ArchiveEntity) => void; onPublish: (id: string) => void; onArchive: (id: string) => void }) {
  const form = useForm({ mode: "controlled", initialValues: { query: "", status: "all" } });
  const showArchived = form.values.status === "archived";
  const visible = useMemo(() => items.filter((item) => {
    const matchesStatus = form.values.status === "archived" ? item.state === "archived" : item.state !== "archived" && (form.values.status === "all" || item.state === form.values.status);
    if (!matchesStatus) return false;
    const content = item.draft ?? item.published;
    const title = content && "title" in content ? content.title : content && "name" in content ? content.name : "";
    return `${title ?? ""} ${item.slug}`.toLowerCase().includes(form.values.query.toLowerCase());
  }), [items, form.values.query, form.values.status]);
  const title = section === "projects" ? "Progetti" : "Persone";
  const canCreate = section === "projects" || !teamFull;
  const active = items.filter((item) => item.state !== "archived");
  const counts = { all: active.length, draft: active.filter((item) => item.state === "draft").length, published: active.filter((item) => item.state === "published").length, archived: items.filter((item) => item.state === "archived").length };
  return <section className="archive-view"><header className="view-header"><div><Text className="eyebrow">Archivio</Text><h1>{title}</h1><Text c="dimmed">{section === "projects" ? "Crea, ordina e prepara i progetti prima della pubblicazione." : "La pagina Persone mantiene il collage con un massimo di tre profili."}</Text></div>{canCreate ? <Button color="orange" onClick={onNew}>{section === "projects" ? "Nuovo progetto" : "Nuova persona"}</Button> : <Tooltip label="Il collage pubblico ospita tre profili: archiviane uno per liberare un posto."><span tabIndex={0} className="disabled-cta"><Button color="orange" disabled>Nuova persona</Button></span></Tooltip>}</header>
    <div className="archive-tools"><TextInput placeholder={`Cerca ${title.toLowerCase()}…`} {...form.getInputProps("query")} /><SegmentedControl aria-label="Filtra per stato" value={form.values.status} onChange={(status) => form.setFieldValue("status", status)} data={[{ value: "all", label: `Tutti ${counts.all}` }, { value: "draft", label: `Bozze ${counts.draft}` }, { value: "published", label: `Online ${counts.published}` }, { value: "archived", label: `Archiviati ${counts.archived}` }]} /></div>
    <div className="archive-list">{visible.length ? visible.map((item, index) => { const content = item.draft ?? item.published; const name = content && "title" in content ? content.title : content && "name" in content ? content.name : "Senza titolo"; const note = content && "subtitle" in content ? content.subtitle : content && "role" in content ? content.role : ""; const image = content && "cover" in content ? content.cover : content && "image" in content ? content.image : ""; const hasPendingChanges = changedSincePublication(item); return <div className="archive-row" key={item.id}><UnstyledButton onClick={() => onOpen(item.id)} className="archive-open">{image && <img src={image} alt="" />}<div className="archive-copy"><Text fw={700}>{name || "Senza titolo"}</Text><Text c="dimmed" size="sm" lineClamp={1}>{note}</Text><Text className="archive-updated" size="xs">Modificato {archiveDate(item.updatedAt)}{hasPendingChanges && item.published ? " · modifiche non online" : ""}{item.slug ? ` · /${item.slug}` : ""}</Text></div><Badge className={`state state-${item.state}`} variant="light">{item.state === "published" ? "Online" : statusLabel(item.state)}</Badge></UnstyledButton>{isAdmin && <Group gap={0} className="archive-actions">{showArchived ? <Button size="xs" variant="default" onClick={() => onRestore(item.id)}>Ripristina</Button> : <><Menu position="bottom-end" withinPortal><Menu.Target><ActionIcon aria-label={`Altre azioni per ${name || "questo contenuto"}`} variant="subtle" color="dark"><IconDots size={17} stroke={1.7} /></ActionIcon></Menu.Target><Menu.Dropdown><Menu.Item onClick={() => onOpen(item.id)}>Apri</Menu.Item>{section === "projects" && <Menu.Item onClick={() => onDuplicate(item)}>Duplica</Menu.Item>}{hasPendingChanges && <Menu.Item onClick={() => onPublish(item.id)}>{item.published ? "Pubblica modifiche" : "Pubblica"}</Menu.Item>}<Menu.Divider /><Menu.Item color="red" onClick={() => onArchive(item.id)}>Archivia</Menu.Item></Menu.Dropdown></Menu><Tooltip label="Sposta su"><ActionIcon aria-label={`Sposta ${name || "elemento"} più in alto`} variant="subtle" color="dark" disabled={index === 0} onClick={() => onMove(item, visible[index - 1])}><IconArrowUp size={17} stroke={1.7} /></ActionIcon></Tooltip><Tooltip label="Sposta giù"><ActionIcon aria-label={`Sposta ${name || "elemento"} più in basso`} variant="subtle" color="dark" disabled={index === visible.length - 1} onClick={() => onMove(item, visible[index + 1])}><IconArrowDown size={17} stroke={1.7} /></ActionIcon></Tooltip></>}</Group>}</div>; }) : <div className="empty-state"><h2>{showArchived ? "Nessun contenuto archiviato." : "Nessun contenuto qui."}</h2><p>{showArchived ? "Gli elementi archiviati compariranno qui e potrai riportarli in bozza." : "Prova un’altra ricerca oppure crea il primo elemento."}</p></div>}</div>
  </section>;
}
